name: "Multi event Pipeline Workflow"

on:
    push:
        branches:
            - master
            - test
    pull_request:
        branches:
            - master
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master/test branch push"
              run: echo "This job runs on push to master/test branch"

    on-pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "This job runs on pull request to master branch"